# Generated by Django 4.0.5 on 2023-12-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_historical_performance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='historical_performance',
            new_name='HistoricalPerformance',
        ),
    ]
