# Generated by Django 4.0.5 on 2023-12-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_historical_performance_historicalperformance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase_order',
            new_name='PurchaseOrder',
        ),
    ]
